// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Drive API (drive/v2)
// Description:
//   Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
// Classes:
//   About
// Documentation:
//   https://developers.google.com/drive/

#include "google/drive_api/about.h"
#include <string>
#include "googleapis/base/integral_types.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/drive_api/user.h"


#include <string>
#include "googleapis/strings/strcat.h"

namespace google_drive_api {
using namespace googleapis;




// Object factory method (static).
About::AboutAdditionalRoleInfo::AboutAdditionalRoleInfoRoleSets* About::AboutAdditionalRoleInfo::AboutAdditionalRoleInfoRoleSets::New() {
  return new client::JsonCppCapsule<AboutAdditionalRoleInfoRoleSets>;
}

// Standard immutable constructor.
About::AboutAdditionalRoleInfo::AboutAdditionalRoleInfoRoleSets::AboutAdditionalRoleInfoRoleSets(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
About::AboutAdditionalRoleInfo::AboutAdditionalRoleInfoRoleSets::AboutAdditionalRoleInfoRoleSets(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
About::AboutAdditionalRoleInfo::AboutAdditionalRoleInfoRoleSets::~AboutAdditionalRoleInfoRoleSets() {
}

// Properties.
// Object factory method (static).
About::AboutAdditionalRoleInfo* About::AboutAdditionalRoleInfo::New() {
  return new client::JsonCppCapsule<AboutAdditionalRoleInfo>;
}

// Standard immutable constructor.
About::AboutAdditionalRoleInfo::AboutAdditionalRoleInfo(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
About::AboutAdditionalRoleInfo::AboutAdditionalRoleInfo(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
About::AboutAdditionalRoleInfo::~AboutAdditionalRoleInfo() {
}

// Properties.

// Object factory method (static).
About::AboutExportFormats* About::AboutExportFormats::New() {
  return new client::JsonCppCapsule<AboutExportFormats>;
}

// Standard immutable constructor.
About::AboutExportFormats::AboutExportFormats(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
About::AboutExportFormats::AboutExportFormats(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
About::AboutExportFormats::~AboutExportFormats() {
}

// Properties.

// Object factory method (static).
About::AboutFeatures* About::AboutFeatures::New() {
  return new client::JsonCppCapsule<AboutFeatures>;
}

// Standard immutable constructor.
About::AboutFeatures::AboutFeatures(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
About::AboutFeatures::AboutFeatures(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
About::AboutFeatures::~AboutFeatures() {
}

// Properties.

// Object factory method (static).
About::AboutImportFormats* About::AboutImportFormats::New() {
  return new client::JsonCppCapsule<AboutImportFormats>;
}

// Standard immutable constructor.
About::AboutImportFormats::AboutImportFormats(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
About::AboutImportFormats::AboutImportFormats(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
About::AboutImportFormats::~AboutImportFormats() {
}

// Properties.

// Object factory method (static).
About::AboutMaxUploadSizes* About::AboutMaxUploadSizes::New() {
  return new client::JsonCppCapsule<AboutMaxUploadSizes>;
}

// Standard immutable constructor.
About::AboutMaxUploadSizes::AboutMaxUploadSizes(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
About::AboutMaxUploadSizes::AboutMaxUploadSizes(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
About::AboutMaxUploadSizes::~AboutMaxUploadSizes() {
}

// Properties.

// Object factory method (static).
About::AboutQuotaBytesByService* About::AboutQuotaBytesByService::New() {
  return new client::JsonCppCapsule<AboutQuotaBytesByService>;
}

// Standard immutable constructor.
About::AboutQuotaBytesByService::AboutQuotaBytesByService(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
About::AboutQuotaBytesByService::AboutQuotaBytesByService(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
About::AboutQuotaBytesByService::~AboutQuotaBytesByService() {
}

// Properties.

// Object factory method (static).
About::AboutTeamDriveThemes* About::AboutTeamDriveThemes::New() {
  return new client::JsonCppCapsule<AboutTeamDriveThemes>;
}

// Standard immutable constructor.
About::AboutTeamDriveThemes::AboutTeamDriveThemes(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
About::AboutTeamDriveThemes::AboutTeamDriveThemes(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
About::AboutTeamDriveThemes::~AboutTeamDriveThemes() {
}

// Properties.
// Object factory method (static).
About* About::New() {
  return new client::JsonCppCapsule<About>;
}

// Standard immutable constructor.
About::About(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
About::About(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
About::~About() {
}

// Properties.

const User About::get_user() const {
   const Json::Value& storage = Storage("user");
   return client::JsonValueToCppValueHelper<User >(storage);
}

User About::mutable_user() {
  Json::Value* storage = MutableStorage("user");
  return client::JsonValueToMutableCppValueHelper<User >(storage);
}
}  // namespace google_drive_api
