// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.0
//   Build date: 2014-11-17 18:43:33 UTC
//   on: 2014-12-12, 14:51:57 UTC
//   C++ generator version:

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Drive API (drive/v2)
// Description:
//   The API to interact with Drive.
// Classes:
//   Comment
// Documentation:
//   https://developers.google.com/drive/

#include "google/drive_api/comment.h"
#include <string>
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/client/util/date_time.h"
#include "googleapis/strings/stringpiece.h"

#include "google/drive_api/comment_reply.h"
#include "google/drive_api/user.h"


#include <string>
#include "googleapis/strings/strcat.h"

namespace google_drive_api {
using namespace googleapis;



// Object factory method (static).
Comment::CommentContext* Comment::CommentContext::New() {
  return new client::JsonCppCapsule<CommentContext>;
}

// Standard immutable constructor.
Comment::CommentContext::CommentContext(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
Comment::CommentContext::CommentContext(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
Comment::CommentContext::~CommentContext() {
}
// Object factory method (static).
Comment* Comment::New() {
  return new client::JsonCppCapsule<Comment>;
}

// Standard immutable constructor.
Comment::Comment(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
Comment::Comment(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
Comment::~Comment() {
}
}  // namespace google_drive_api
