// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Drive API (drive/v2)
// Generated from:
//   Version: v2
//   Revision: 20170512
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_DRIVE_API_PERMISSION_H_
#define  GOOGLE_DRIVE_API_PERMISSION_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/client/util/date_time.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_drive_api {
using namespace googleapis;

/**
 * A permission for a file.
 *
 * @ingroup DataObject
 */
class Permission : public client::JsonCppData {
 public:
  /**
   * No description provided.
   *
   * @ingroup DataObject
   */
  class PermissionTeamDrivePermissionDetails : public client::JsonCppData {
   public:
    /**
     * Creates a new default instance.
     *
     * @return Ownership is passed back to the caller.
     */
    static PermissionTeamDrivePermissionDetails* New();

    /**
     * Standard constructor for an immutable data object instance.
     *
     * @param[in] storage  The underlying data storage for this instance.
     */
    explicit PermissionTeamDrivePermissionDetails(const Json::Value& storage);

    /**
     * Standard constructor for a mutable data object instance.
     *
     * @param[in] storage  The underlying data storage for this instance.
     */
    explicit PermissionTeamDrivePermissionDetails(Json::Value* storage);

    /**
     * Standard destructor.
     */
    virtual ~PermissionTeamDrivePermissionDetails();

    /**
     * Returns a string denoting the type of this data object.
     *
     * @return
     * <code>google_drive_api::PermissionTeamDrivePermissionDetails</code>
     */
    const StringPiece GetTypeName() const {
      return StringPiece("google_drive_api::PermissionTeamDrivePermissionDetails");
    }

    /**
     * Determine if the '<code>additionalRoles</code>' attribute was set.
     *
     * @return true if the '<code>additionalRoles</code>' attribute was set.
     */
    bool has_additional_roles() const {
      return Storage().isMember("additionalRoles");
    }

    /**
     * Clears the '<code>additionalRoles</code>' attribute.
     */
    void clear_additional_roles() {
      MutableStorage()->removeMember("additionalRoles");
    }


    /**
     * Get a reference to the value of the '<code>additionalRoles</code>'
     * attribute.
     */
    const client::JsonCppArray<string > get_additional_roles() const {
       const Json::Value& storage = Storage("additionalRoles");
      return client::JsonValueToCppValueHelper<client::JsonCppArray<string > >(storage);
    }

    /**
     * Gets a reference to a mutable value of the '<code>additionalRoles</code>'
     * property.
     *
     * Additional roles for this user. Only commenter is currently possible,
     * though more may be supported in the future.
     *
     * @return The result can be modified to change the attribute value.
     */
    client::JsonCppArray<string > mutable_additionalRoles() {
      Json::Value* storage = MutableStorage("additionalRoles");
      return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<string > >(storage);
    }

    /**
     * Determine if the '<code>inherited</code>' attribute was set.
     *
     * @return true if the '<code>inherited</code>' attribute was set.
     */
    bool has_inherited() const {
      return Storage().isMember("inherited");
    }

    /**
     * Clears the '<code>inherited</code>' attribute.
     */
    void clear_inherited() {
      MutableStorage()->removeMember("inherited");
    }


    /**
     * Get the value of the '<code>inherited</code>' attribute.
     */
    bool get_inherited() const {
      const Json::Value& storage = Storage("inherited");
      return client::JsonValueToCppValueHelper<bool >(storage);
    }

    /**
     * Change the '<code>inherited</code>' attribute.
     *
     * Whether this permission is inherited. This field is always populated.
     * This is an output-only field.
     *
     * @param[in] value The new value.
     */
    void set_inherited(bool value) {
      client::SetJsonValueFromCppValueHelper<bool >(
        value, MutableStorage("inherited"));
    }

    /**
     * Determine if the '<code>inheritedFrom</code>' attribute was set.
     *
     * @return true if the '<code>inheritedFrom</code>' attribute was set.
     */
    bool has_inherited_from() const {
      return Storage().isMember("inheritedFrom");
    }

    /**
     * Clears the '<code>inheritedFrom</code>' attribute.
     */
    void clear_inherited_from() {
      MutableStorage()->removeMember("inheritedFrom");
    }


    /**
     * Get the value of the '<code>inheritedFrom</code>' attribute.
     */
    const StringPiece get_inherited_from() const {
      const Json::Value& v = Storage("inheritedFrom");
      if (v == Json::Value::null) return StringPiece("");
      return StringPiece(v.asCString());
    }

    /**
     * Change the '<code>inheritedFrom</code>' attribute.
     *
     * The ID of the item from which this permission is inherited. This is an
     * output-only field and is only populated for members of the Team Drive.
     *
     * @param[in] value The new value.
     */
    void set_inherited_from(const StringPiece& value) {
      *MutableStorage("inheritedFrom") = value.data();
    }

    /**
     * Determine if the '<code>role</code>' attribute was set.
     *
     * @return true if the '<code>role</code>' attribute was set.
     */
    bool has_role() const {
      return Storage().isMember("role");
    }

    /**
     * Clears the '<code>role</code>' attribute.
     */
    void clear_role() {
      MutableStorage()->removeMember("role");
    }


    /**
     * Get the value of the '<code>role</code>' attribute.
     */
    const StringPiece get_role() const {
      const Json::Value& v = Storage("role");
      if (v == Json::Value::null) return StringPiece("");
      return StringPiece(v.asCString());
    }

    /**
     * Change the '<code>role</code>' attribute.
     *
     * The primary role for this user. While new values may be added in the
     * future, the following are currently possible:
     * - organizer
     * - reader
     * - writer.
     *
     * @param[in] value The new value.
     */
    void set_role(const StringPiece& value) {
      *MutableStorage("role") = value.data();
    }

    /**
     * Determine if the '<code>teamDrivePermissionType</code>' attribute was
     * set.
     *
     * @return true if the '<code>teamDrivePermissionType</code>' attribute was
     * set.
     */
    bool has_team_drive_permission_type() const {
      return Storage().isMember("teamDrivePermissionType");
    }

    /**
     * Clears the '<code>teamDrivePermissionType</code>' attribute.
     */
    void clear_team_drive_permission_type() {
      MutableStorage()->removeMember("teamDrivePermissionType");
    }


    /**
     * Get the value of the '<code>teamDrivePermissionType</code>' attribute.
     */
    const StringPiece get_team_drive_permission_type() const {
      const Json::Value& v = Storage("teamDrivePermissionType");
      if (v == Json::Value::null) return StringPiece("");
      return StringPiece(v.asCString());
    }

    /**
     * Change the '<code>teamDrivePermissionType</code>' attribute.
     *
     * The Team Drive permission type for this user. While new values may be
     * added in future, the following are currently possible:
     * - file
     * - member.
     *
     * @param[in] value The new value.
     */
    void set_team_drive_permission_type(const StringPiece& value) {
      *MutableStorage("teamDrivePermissionType") = value.data();
    }

   private:
    void operator=(const PermissionTeamDrivePermissionDetails&);
  };  // PermissionTeamDrivePermissionDetails
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Permission* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Permission(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Permission(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Permission();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_drive_api::Permission</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_drive_api::Permission");
  }

  /**
   * Determine if the '<code>additionalRoles</code>' attribute was set.
   *
   * @return true if the '<code>additionalRoles</code>' attribute was set.
   */
  bool has_additional_roles() const {
    return Storage().isMember("additionalRoles");
  }

  /**
   * Clears the '<code>additionalRoles</code>' attribute.
   */
  void clear_additional_roles() {
    MutableStorage()->removeMember("additionalRoles");
  }


  /**
   * Get a reference to the value of the '<code>additionalRoles</code>'
   * attribute.
   */
  const client::JsonCppArray<string > get_additional_roles() const {
     const Json::Value& storage = Storage("additionalRoles");
    return client::JsonValueToCppValueHelper<client::JsonCppArray<string > >(storage);
  }

  /**
   * Gets a reference to a mutable value of the '<code>additionalRoles</code>'
   * property.
   *
   * Additional roles for this user. Only commenter is currently allowed, though
   * more may be supported in the future.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<string > mutable_additionalRoles() {
    Json::Value* storage = MutableStorage("additionalRoles");
    return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<string > >(storage);
  }

  /**
   * Determine if the '<code>authKey</code>' attribute was set.
   *
   * @return true if the '<code>authKey</code>' attribute was set.
   */
  bool has_auth_key() const {
    return Storage().isMember("authKey");
  }

  /**
   * Clears the '<code>authKey</code>' attribute.
   */
  void clear_auth_key() {
    MutableStorage()->removeMember("authKey");
  }


  /**
   * Get the value of the '<code>authKey</code>' attribute.
   */
  const StringPiece get_auth_key() const {
    const Json::Value& v = Storage("authKey");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>authKey</code>' attribute.
   *
   * The authkey parameter required for this permission.
   *
   * @param[in] value The new value.
   */
  void set_auth_key(const StringPiece& value) {
    *MutableStorage("authKey") = value.data();
  }

  /**
   * Determine if the '<code>deleted</code>' attribute was set.
   *
   * @return true if the '<code>deleted</code>' attribute was set.
   */
  bool has_deleted() const {
    return Storage().isMember("deleted");
  }

  /**
   * Clears the '<code>deleted</code>' attribute.
   */
  void clear_deleted() {
    MutableStorage()->removeMember("deleted");
  }


  /**
   * Get the value of the '<code>deleted</code>' attribute.
   */
  bool get_deleted() const {
    const Json::Value& storage = Storage("deleted");
    return client::JsonValueToCppValueHelper<bool >(storage);
  }

  /**
   * Change the '<code>deleted</code>' attribute.
   *
   * Whether the account associated with this permission has been deleted. This
   * field only pertains to user and group permissions.
   *
   * @param[in] value The new value.
   */
  void set_deleted(bool value) {
    client::SetJsonValueFromCppValueHelper<bool >(
      value, MutableStorage("deleted"));
  }

  /**
   * Determine if the '<code>domain</code>' attribute was set.
   *
   * @return true if the '<code>domain</code>' attribute was set.
   */
  bool has_domain() const {
    return Storage().isMember("domain");
  }

  /**
   * Clears the '<code>domain</code>' attribute.
   */
  void clear_domain() {
    MutableStorage()->removeMember("domain");
  }


  /**
   * Get the value of the '<code>domain</code>' attribute.
   */
  const StringPiece get_domain() const {
    const Json::Value& v = Storage("domain");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>domain</code>' attribute.
   *
   * The domain name of the entity this permission refers to. This is an output-
   * only field which is present when the permission type is user, group or
   * domain.
   *
   * @param[in] value The new value.
   */
  void set_domain(const StringPiece& value) {
    *MutableStorage("domain") = value.data();
  }

  /**
   * Determine if the '<code>emailAddress</code>' attribute was set.
   *
   * @return true if the '<code>emailAddress</code>' attribute was set.
   */
  bool has_email_address() const {
    return Storage().isMember("emailAddress");
  }

  /**
   * Clears the '<code>emailAddress</code>' attribute.
   */
  void clear_email_address() {
    MutableStorage()->removeMember("emailAddress");
  }


  /**
   * Get the value of the '<code>emailAddress</code>' attribute.
   */
  const StringPiece get_email_address() const {
    const Json::Value& v = Storage("emailAddress");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>emailAddress</code>' attribute.
   *
   * The email address of the user or group this permission refers to. This is
   * an output-only field which is present when the permission type is user or
   * group.
   *
   * @param[in] value The new value.
   */
  void set_email_address(const StringPiece& value) {
    *MutableStorage("emailAddress") = value.data();
  }

  /**
   * Determine if the '<code>etag</code>' attribute was set.
   *
   * @return true if the '<code>etag</code>' attribute was set.
   */
  bool has_etag() const {
    return Storage().isMember("etag");
  }

  /**
   * Clears the '<code>etag</code>' attribute.
   */
  void clear_etag() {
    MutableStorage()->removeMember("etag");
  }


  /**
   * Get the value of the '<code>etag</code>' attribute.
   */
  const StringPiece get_etag() const {
    const Json::Value& v = Storage("etag");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>etag</code>' attribute.
   *
   * The ETag of the permission.
   *
   * @param[in] value The new value.
   */
  void set_etag(const StringPiece& value) {
    *MutableStorage("etag") = value.data();
  }

  /**
   * Determine if the '<code>expirationDate</code>' attribute was set.
   *
   * @return true if the '<code>expirationDate</code>' attribute was set.
   */
  bool has_expiration_date() const {
    return Storage().isMember("expirationDate");
  }

  /**
   * Clears the '<code>expirationDate</code>' attribute.
   */
  void clear_expiration_date() {
    MutableStorage()->removeMember("expirationDate");
  }


  /**
   * Get the value of the '<code>expirationDate</code>' attribute.
   */
  client::DateTime get_expiration_date() const {
    const Json::Value& storage = Storage("expirationDate");
    return client::JsonValueToCppValueHelper<client::DateTime >(storage);
  }

  /**
   * Change the '<code>expirationDate</code>' attribute.
   *
   * The time at which this permission will expire (RFC 3339 date-time).
   * Expiration dates have the following restrictions:
   * - They can only be set on user and group permissions
   * - The date must be in the future
   * - The date cannot be more than a year in the future
   * - The date can only be set on drive.permissions.update requests.
   *
   * @param[in] value The new value.
   */
  void set_expiration_date(client::DateTime value) {
    client::SetJsonValueFromCppValueHelper<client::DateTime >(
      value, MutableStorage("expirationDate"));
  }

  /**
   * Determine if the '<code>id</code>' attribute was set.
   *
   * @return true if the '<code>id</code>' attribute was set.
   */
  bool has_id() const {
    return Storage().isMember("id");
  }

  /**
   * Clears the '<code>id</code>' attribute.
   */
  void clear_id() {
    MutableStorage()->removeMember("id");
  }


  /**
   * Get the value of the '<code>id</code>' attribute.
   */
  const StringPiece get_id() const {
    const Json::Value& v = Storage("id");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>id</code>' attribute.
   *
   * The ID of the user this permission refers to, and identical to the
   * permissionId in the About and Files resources. When making a
   * drive.permissions.insert request, exactly one of the id or value fields
   * must be specified unless the permission type is anyone, in which case both
   * id and value are ignored.
   *
   * @param[in] value The new value.
   */
  void set_id(const StringPiece& value) {
    *MutableStorage("id") = value.data();
  }

  /**
   * Determine if the '<code>kind</code>' attribute was set.
   *
   * @return true if the '<code>kind</code>' attribute was set.
   */
  bool has_kind() const {
    return Storage().isMember("kind");
  }

  /**
   * Clears the '<code>kind</code>' attribute.
   */
  void clear_kind() {
    MutableStorage()->removeMember("kind");
  }


  /**
   * Get the value of the '<code>kind</code>' attribute.
   */
  const StringPiece get_kind() const {
    const Json::Value& v = Storage("kind");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>kind</code>' attribute.
   *
   * This is always drive#permission.
   *
   * @param[in] value The new value.
   */
  void set_kind(const StringPiece& value) {
    *MutableStorage("kind") = value.data();
  }

  /**
   * Determine if the '<code>name</code>' attribute was set.
   *
   * @return true if the '<code>name</code>' attribute was set.
   */
  bool has_name() const {
    return Storage().isMember("name");
  }

  /**
   * Clears the '<code>name</code>' attribute.
   */
  void clear_name() {
    MutableStorage()->removeMember("name");
  }


  /**
   * Get the value of the '<code>name</code>' attribute.
   */
  const StringPiece get_name() const {
    const Json::Value& v = Storage("name");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>name</code>' attribute.
   *
   * The name for this permission.
   *
   * @param[in] value The new value.
   */
  void set_name(const StringPiece& value) {
    *MutableStorage("name") = value.data();
  }

  /**
   * Determine if the '<code>photoLink</code>' attribute was set.
   *
   * @return true if the '<code>photoLink</code>' attribute was set.
   */
  bool has_photo_link() const {
    return Storage().isMember("photoLink");
  }

  /**
   * Clears the '<code>photoLink</code>' attribute.
   */
  void clear_photo_link() {
    MutableStorage()->removeMember("photoLink");
  }


  /**
   * Get the value of the '<code>photoLink</code>' attribute.
   */
  const StringPiece get_photo_link() const {
    const Json::Value& v = Storage("photoLink");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>photoLink</code>' attribute.
   *
   * A link to the profile photo, if available.
   *
   * @param[in] value The new value.
   */
  void set_photo_link(const StringPiece& value) {
    *MutableStorage("photoLink") = value.data();
  }

  /**
   * Determine if the '<code>role</code>' attribute was set.
   *
   * @return true if the '<code>role</code>' attribute was set.
   */
  bool has_role() const {
    return Storage().isMember("role");
  }

  /**
   * Clears the '<code>role</code>' attribute.
   */
  void clear_role() {
    MutableStorage()->removeMember("role");
  }


  /**
   * Get the value of the '<code>role</code>' attribute.
   */
  const StringPiece get_role() const {
    const Json::Value& v = Storage("role");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>role</code>' attribute.
   *
   * The primary role for this user. While new values may be supported in the
   * future, the following are currently allowed:
   * - organizer
   * - owner
   * - reader
   * - writer.
   *
   * @param[in] value The new value.
   */
  void set_role(const StringPiece& value) {
    *MutableStorage("role") = value.data();
  }

  /**
   * Determine if the '<code>selfLink</code>' attribute was set.
   *
   * @return true if the '<code>selfLink</code>' attribute was set.
   */
  bool has_self_link() const {
    return Storage().isMember("selfLink");
  }

  /**
   * Clears the '<code>selfLink</code>' attribute.
   */
  void clear_self_link() {
    MutableStorage()->removeMember("selfLink");
  }


  /**
   * Get the value of the '<code>selfLink</code>' attribute.
   */
  const StringPiece get_self_link() const {
    const Json::Value& v = Storage("selfLink");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>selfLink</code>' attribute.
   *
   * A link back to this permission.
   *
   * @param[in] value The new value.
   */
  void set_self_link(const StringPiece& value) {
    *MutableStorage("selfLink") = value.data();
  }

  /**
   * Determine if the '<code>teamDrivePermissionDetails</code>' attribute was
   * set.
   *
   * @return true if the '<code>teamDrivePermissionDetails</code>' attribute was
   * set.
   */
  bool has_team_drive_permission_details() const {
    return Storage().isMember("teamDrivePermissionDetails");
  }

  /**
   * Clears the '<code>teamDrivePermissionDetails</code>' attribute.
   */
  void clear_team_drive_permission_details() {
    MutableStorage()->removeMember("teamDrivePermissionDetails");
  }


  /**
   * Get a reference to the value of the
   * '<code>teamDrivePermissionDetails</code>' attribute.
   */
  const client::JsonCppArray<PermissionTeamDrivePermissionDetails > get_team_drive_permission_details() const {
     const Json::Value& storage = Storage("teamDrivePermissionDetails");
    return client::JsonValueToCppValueHelper<client::JsonCppArray<PermissionTeamDrivePermissionDetails > >(storage);
  }

  /**
   * Gets a reference to a mutable value of the
   * '<code>teamDrivePermissionDetails</code>' property.
   *
   * Details of whether the permissions on this Team Drive item are inherited or
   * directly on this item. This is an output-only field which is present only
   * for Team Drive items.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<PermissionTeamDrivePermissionDetails > mutable_teamDrivePermissionDetails() {
    Json::Value* storage = MutableStorage("teamDrivePermissionDetails");
    return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<PermissionTeamDrivePermissionDetails > >(storage);
  }

  /**
   * Determine if the '<code>type</code>' attribute was set.
   *
   * @return true if the '<code>type</code>' attribute was set.
   */
  bool has_type() const {
    return Storage().isMember("type");
  }

  /**
   * Clears the '<code>type</code>' attribute.
   */
  void clear_type() {
    MutableStorage()->removeMember("type");
  }


  /**
   * Get the value of the '<code>type</code>' attribute.
   */
  const StringPiece get_type() const {
    const Json::Value& v = Storage("type");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>type</code>' attribute.
   *
   * The account type. Allowed values are:
   * - user
   * - group
   * - domain
   * - anyone.
   *
   * @param[in] value The new value.
   */
  void set_type(const StringPiece& value) {
    *MutableStorage("type") = value.data();
  }

  /**
   * Determine if the '<code>value</code>' attribute was set.
   *
   * @return true if the '<code>value</code>' attribute was set.
   */
  bool has_value() const {
    return Storage().isMember("value");
  }

  /**
   * Clears the '<code>value</code>' attribute.
   */
  void clear_value() {
    MutableStorage()->removeMember("value");
  }


  /**
   * Get the value of the '<code>value</code>' attribute.
   */
  const StringPiece get_value() const {
    const Json::Value& v = Storage("value");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>value</code>' attribute.
   *
   * The email address or domain name for the entity. This is used during
   * inserts and is not populated in responses. When making a
   * drive.permissions.insert request, exactly one of the id or value fields
   * must be specified unless the permission type is anyone, in which case both
   * id and value are ignored.
   *
   * @param[in] value The new value.
   */
  void set_value(const StringPiece& value) {
    *MutableStorage("value") = value.data();
  }

  /**
   * Determine if the '<code>withLink</code>' attribute was set.
   *
   * @return true if the '<code>withLink</code>' attribute was set.
   */
  bool has_with_link() const {
    return Storage().isMember("withLink");
  }

  /**
   * Clears the '<code>withLink</code>' attribute.
   */
  void clear_with_link() {
    MutableStorage()->removeMember("withLink");
  }


  /**
   * Get the value of the '<code>withLink</code>' attribute.
   */
  bool get_with_link() const {
    const Json::Value& storage = Storage("withLink");
    return client::JsonValueToCppValueHelper<bool >(storage);
  }

  /**
   * Change the '<code>withLink</code>' attribute.
   *
   * Whether the link is required for this permission.
   *
   * @param[in] value The new value.
   */
  void set_with_link(bool value) {
    client::SetJsonValueFromCppValueHelper<bool >(
      value, MutableStorage("withLink"));
  }

 private:
  void operator=(const Permission&);
};  // Permission
}  // namespace google_drive_api
#endif  // GOOGLE_DRIVE_API_PERMISSION_H_
