// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   YouTube Data API (youtube/v3)
// Generated from:
//   Version: v3
//   Revision: 20170130
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_YOUTUBE_API_CHANNEL_TOPIC_DETAILS_H_
#define  GOOGLE_YOUTUBE_API_CHANNEL_TOPIC_DETAILS_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_youtube_api {
using namespace googleapis;

/**
 * Freebase topic information related to the channel.
 *
 * @ingroup DataObject
 */
class ChannelTopicDetails : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static ChannelTopicDetails* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ChannelTopicDetails(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ChannelTopicDetails(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~ChannelTopicDetails();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_youtube_api::ChannelTopicDetails</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_youtube_api::ChannelTopicDetails");
  }

  /**
   * Determine if the '<code>topicCategories</code>' attribute was set.
   *
   * @return true if the '<code>topicCategories</code>' attribute was set.
   */
  bool has_topic_categories() const {
    return Storage().isMember("topicCategories");
  }

  /**
   * Clears the '<code>topicCategories</code>' attribute.
   */
  void clear_topic_categories() {
    MutableStorage()->removeMember("topicCategories");
  }


  /**
   * Get a reference to the value of the '<code>topicCategories</code>'
   * attribute.
   */
  const client::JsonCppArray<string > get_topic_categories() const {
     const Json::Value& storage = Storage("topicCategories");
    return client::JsonValueToCppValueHelper<client::JsonCppArray<string > >(storage);
  }

  /**
   * Gets a reference to a mutable value of the '<code>topicCategories</code>'
   * property.
   *
   * A list of Wikipedia URLs that describe the channel's content.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<string > mutable_topicCategories() {
    Json::Value* storage = MutableStorage("topicCategories");
    return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<string > >(storage);
  }

  /**
   * Determine if the '<code>topicIds</code>' attribute was set.
   *
   * @return true if the '<code>topicIds</code>' attribute was set.
   */
  bool has_topic_ids() const {
    return Storage().isMember("topicIds");
  }

  /**
   * Clears the '<code>topicIds</code>' attribute.
   */
  void clear_topic_ids() {
    MutableStorage()->removeMember("topicIds");
  }


  /**
   * Get a reference to the value of the '<code>topicIds</code>' attribute.
   */
  const client::JsonCppArray<string > get_topic_ids() const {
     const Json::Value& storage = Storage("topicIds");
    return client::JsonValueToCppValueHelper<client::JsonCppArray<string > >(storage);
  }

  /**
   * Gets a reference to a mutable value of the '<code>topicIds</code>'
   * property.
   *
   * A list of Freebase topic IDs associated with the channel. You can retrieve
   * information about each topic using the Freebase Topic API.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<string > mutable_topicIds() {
    Json::Value* storage = MutableStorage("topicIds");
    return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<string > >(storage);
  }

 private:
  void operator=(const ChannelTopicDetails&);
};  // ChannelTopicDetails
}  // namespace google_youtube_api
#endif  // GOOGLE_YOUTUBE_API_CHANNEL_TOPIC_DETAILS_H_
