// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   C++ generator version: 0.1.3

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   YouTube Data API (youtube/v3)
// Generated from:
//   Version: v3
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.3
#ifndef  GOOGLE_YOUTUBE_API_CHANNEL_BRANDING_SETTINGS_H_
#define  GOOGLE_YOUTUBE_API_CHANNEL_BRANDING_SETTINGS_H_

#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/youtube_api/channel_settings.h"
#include "google/youtube_api/image_settings.h"
#include "google/youtube_api/property_value.h"
#include "google/youtube_api/watch_settings.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_youtube_api {
using namespace googleapis;

/**
 * Branding properties of a YouTube channel.
 *
 * @ingroup DataObject
 */
class ChannelBrandingSettings : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static ChannelBrandingSettings* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ChannelBrandingSettings(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ChannelBrandingSettings(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~ChannelBrandingSettings();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_youtube_api::ChannelBrandingSettings</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_youtube_api::ChannelBrandingSettings");
  }

  /**
   * Determine if the '<code>channel</code>' attribute was set.
   *
   * @return true if the '<code>channel</code>' attribute was set.
   */
  bool has_channel() const {
    return Storage().isMember("channel");
  }

  /**
   * Clears the '<code>channel</code>' attribute.
   */
  void clear_channel() {
    MutableStorage()->removeMember("channel");
  }


  /**
   * Get a reference to the value of the '<code>channel</code>' attribute.
   */
  const ChannelSettings get_channel() const;

  /**
   * Gets a reference to a mutable value of the '<code>channel</code>' property.
   *
   * Branding properties for the channel view.
   *
   * @return The result can be modified to change the attribute value.
   */
  ChannelSettings mutable_channel();

  /**
   * Determine if the '<code>hints</code>' attribute was set.
   *
   * @return true if the '<code>hints</code>' attribute was set.
   */
  bool has_hints() const {
    return Storage().isMember("hints");
  }

  /**
   * Clears the '<code>hints</code>' attribute.
   */
  void clear_hints() {
    MutableStorage()->removeMember("hints");
  }


  /**
   * Get a reference to the value of the '<code>hints</code>' attribute.
   */
  const client::JsonCppArray<PropertyValue > get_hints() const;

  /**
   * Gets a reference to a mutable value of the '<code>hints</code>' property.
   *
   * Additional experimental branding properties.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<PropertyValue > mutable_hints();

  /**
   * Determine if the '<code>image</code>' attribute was set.
   *
   * @return true if the '<code>image</code>' attribute was set.
   */
  bool has_image() const {
    return Storage().isMember("image");
  }

  /**
   * Clears the '<code>image</code>' attribute.
   */
  void clear_image() {
    MutableStorage()->removeMember("image");
  }


  /**
   * Get a reference to the value of the '<code>image</code>' attribute.
   */
  const ImageSettings get_image() const;

  /**
   * Gets a reference to a mutable value of the '<code>image</code>' property.
   *
   * Branding properties for branding images.
   *
   * @return The result can be modified to change the attribute value.
   */
  ImageSettings mutable_image();

  /**
   * Determine if the '<code>watch</code>' attribute was set.
   *
   * @return true if the '<code>watch</code>' attribute was set.
   */
  bool has_watch() const {
    return Storage().isMember("watch");
  }

  /**
   * Clears the '<code>watch</code>' attribute.
   */
  void clear_watch() {
    MutableStorage()->removeMember("watch");
  }


  /**
   * Get a reference to the value of the '<code>watch</code>' attribute.
   */
  const WatchSettings get_watch() const;

  /**
   * Gets a reference to a mutable value of the '<code>watch</code>' property.
   *
   * Branding properties for the watch page.
   *
   * @return The result can be modified to change the attribute value.
   */
  WatchSettings mutable_watch();

 private:
  void operator=(const ChannelBrandingSettings&);
};  // ChannelBrandingSettings
}  // namespace google_youtube_api
#endif  // GOOGLE_YOUTUBE_API_CHANNEL_BRANDING_SETTINGS_H_
