// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   C++ generator version: 0.1.3

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   YouTube Data API (youtube/v3)
// Generated from:
//   Version: v3
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.3
#ifndef  GOOGLE_YOUTUBE_API_LIVE_CHAT_BAN_SNIPPET_H_
#define  GOOGLE_YOUTUBE_API_LIVE_CHAT_BAN_SNIPPET_H_

#include <string>
#include "googleapis/base/integral_types.h"
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/youtube_api/channel_profile_details.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_youtube_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class LiveChatBanSnippet : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static LiveChatBanSnippet* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit LiveChatBanSnippet(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit LiveChatBanSnippet(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~LiveChatBanSnippet();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_youtube_api::LiveChatBanSnippet</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_youtube_api::LiveChatBanSnippet");
  }

  /**
   * Determine if the '<code>banDurationSeconds</code>' attribute was set.
   *
   * @return true if the '<code>banDurationSeconds</code>' attribute was set.
   */
  bool has_ban_duration_seconds() const {
    return Storage().isMember("banDurationSeconds");
  }

  /**
   * Clears the '<code>banDurationSeconds</code>' attribute.
   */
  void clear_ban_duration_seconds() {
    MutableStorage()->removeMember("banDurationSeconds");
  }


  /**
   * Get the value of the '<code>banDurationSeconds</code>' attribute.
   */
  uint64 get_ban_duration_seconds() const {
    const Json::Value& storage = Storage("banDurationSeconds");
    return client::JsonValueToCppValueHelper<uint64 >(storage);
  }

  /**
   * Change the '<code>banDurationSeconds</code>' attribute.
   *
   * The duration of a ban, only filled if the ban has type TEMPORARY.
   *
   * @param[in] value The new value.
   */
  void set_ban_duration_seconds(uint64 value) {
    client::SetJsonValueFromCppValueHelper<uint64 >(
      value, MutableStorage("banDurationSeconds"));
  }

  /**
   * Determine if the '<code>bannedUserDetails</code>' attribute was set.
   *
   * @return true if the '<code>bannedUserDetails</code>' attribute was set.
   */
  bool has_banned_user_details() const {
    return Storage().isMember("bannedUserDetails");
  }

  /**
   * Clears the '<code>bannedUserDetails</code>' attribute.
   */
  void clear_banned_user_details() {
    MutableStorage()->removeMember("bannedUserDetails");
  }


  /**
   * Get a reference to the value of the '<code>bannedUserDetails</code>'
   * attribute.
   */
  const ChannelProfileDetails get_banned_user_details() const;

  /**
   * Gets a reference to a mutable value of the '<code>bannedUserDetails</code>'
   * property.
   * @return The result can be modified to change the attribute value.
   */
  ChannelProfileDetails mutable_bannedUserDetails();

  /**
   * Determine if the '<code>liveChatId</code>' attribute was set.
   *
   * @return true if the '<code>liveChatId</code>' attribute was set.
   */
  bool has_live_chat_id() const {
    return Storage().isMember("liveChatId");
  }

  /**
   * Clears the '<code>liveChatId</code>' attribute.
   */
  void clear_live_chat_id() {
    MutableStorage()->removeMember("liveChatId");
  }


  /**
   * Get the value of the '<code>liveChatId</code>' attribute.
   */
  const StringPiece get_live_chat_id() const {
    const Json::Value& v = Storage("liveChatId");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>liveChatId</code>' attribute.
   *
   * The chat this ban is pertinent to.
   *
   * @param[in] value The new value.
   */
  void set_live_chat_id(const StringPiece& value) {
    *MutableStorage("liveChatId") = value.data();
  }

  /**
   * Determine if the '<code>type</code>' attribute was set.
   *
   * @return true if the '<code>type</code>' attribute was set.
   */
  bool has_type() const {
    return Storage().isMember("type");
  }

  /**
   * Clears the '<code>type</code>' attribute.
   */
  void clear_type() {
    MutableStorage()->removeMember("type");
  }


  /**
   * Get the value of the '<code>type</code>' attribute.
   */
  const StringPiece get_type() const {
    const Json::Value& v = Storage("type");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>type</code>' attribute.
   *
   * The type of ban.
   *
   * @param[in] value The new value.
   */
  void set_type(const StringPiece& value) {
    *MutableStorage("type") = value.data();
  }

 private:
  void operator=(const LiveChatBanSnippet&);
};  // LiveChatBanSnippet
}  // namespace google_youtube_api
#endif  // GOOGLE_YOUTUBE_API_LIVE_CHAT_BAN_SNIPPET_H_
