// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   YouTube Data API (youtube/v3)
// Description:
//   Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.
// Classes:
//   LiveBroadcastContentDetails
// Documentation:
//   https://developers.google.com/youtube/v3

#include "google/youtube_api/live_broadcast_content_details.h"
#include <string>
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/client/util/date_time.h"
#include "googleapis/strings/stringpiece.h"

#include "google/youtube_api/monitor_stream_info.h"


#include <string>
#include "googleapis/strings/strcat.h"

namespace google_youtube_api {
using namespace googleapis;


// Object factory method (static).
LiveBroadcastContentDetails* LiveBroadcastContentDetails::New() {
  return new client::JsonCppCapsule<LiveBroadcastContentDetails>;
}

// Standard immutable constructor.
LiveBroadcastContentDetails::LiveBroadcastContentDetails(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
LiveBroadcastContentDetails::LiveBroadcastContentDetails(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
LiveBroadcastContentDetails::~LiveBroadcastContentDetails() {
}

// Properties.

const MonitorStreamInfo LiveBroadcastContentDetails::get_monitor_stream() const {
   const Json::Value& storage = Storage("monitorStream");
   return client::JsonValueToCppValueHelper<MonitorStreamInfo >(storage);
}

MonitorStreamInfo LiveBroadcastContentDetails::mutable_monitorStream() {
  Json::Value* storage = MutableStorage("monitorStream");
  return client::JsonValueToMutableCppValueHelper<MonitorStreamInfo >(storage);
}
}  // namespace google_youtube_api
