// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   YouTube Data API (youtube/v3)
// Description:
//   Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.
// Classes:
//   PromotedItem
// Documentation:
//   https://developers.google.com/youtube/v3

#include "google/youtube_api/promoted_item.h"
#include <string>
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/youtube_api/invideo_timing.h"
#include "google/youtube_api/promoted_item_id.h"


#include <string>
#include "googleapis/strings/strcat.h"

namespace google_youtube_api {
using namespace googleapis;


// Object factory method (static).
PromotedItem* PromotedItem::New() {
  return new client::JsonCppCapsule<PromotedItem>;
}

// Standard immutable constructor.
PromotedItem::PromotedItem(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
PromotedItem::PromotedItem(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
PromotedItem::~PromotedItem() {
}

// Properties.

const PromotedItemId PromotedItem::get_id() const {
   const Json::Value& storage = Storage("id");
   return client::JsonValueToCppValueHelper<PromotedItemId >(storage);
}

PromotedItemId PromotedItem::mutable_id() {
  Json::Value* storage = MutableStorage("id");
  return client::JsonValueToMutableCppValueHelper<PromotedItemId >(storage);
}

const InvideoTiming PromotedItem::get_timing() const {
   const Json::Value& storage = Storage("timing");
   return client::JsonValueToCppValueHelper<InvideoTiming >(storage);
}

InvideoTiming PromotedItem::mutable_timing() {
  Json::Value* storage = MutableStorage("timing");
  return client::JsonValueToMutableCppValueHelper<InvideoTiming >(storage);
}
}  // namespace google_youtube_api
