// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   YouTube Data API (youtube/v3)
// Description:
//   Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.
// Classes:
//   VideoFileDetails
// Documentation:
//   https://developers.google.com/youtube/v3

#include "google/youtube_api/video_file_details.h"
#include <string>
#include "googleapis/base/integral_types.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/youtube_api/video_file_details_audio_stream.h"
#include "google/youtube_api/video_file_details_video_stream.h"


#include <string>
#include "googleapis/strings/strcat.h"

namespace google_youtube_api {
using namespace googleapis;


// Object factory method (static).
VideoFileDetails* VideoFileDetails::New() {
  return new client::JsonCppCapsule<VideoFileDetails>;
}

// Standard immutable constructor.
VideoFileDetails::VideoFileDetails(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
VideoFileDetails::VideoFileDetails(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
VideoFileDetails::~VideoFileDetails() {
}

// Properties.

const client::JsonCppArray<VideoFileDetailsAudioStream > VideoFileDetails::get_audio_streams() const {
   const Json::Value& storage = Storage("audioStreams");
   return client::JsonValueToCppValueHelper<client::JsonCppArray<VideoFileDetailsAudioStream > >(storage);
}

client::JsonCppArray<VideoFileDetailsAudioStream > VideoFileDetails::mutable_audioStreams() {
  Json::Value* storage = MutableStorage("audioStreams");
  return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<VideoFileDetailsAudioStream > >(storage);
}

const client::JsonCppArray<VideoFileDetailsVideoStream > VideoFileDetails::get_video_streams() const {
   const Json::Value& storage = Storage("videoStreams");
   return client::JsonValueToCppValueHelper<client::JsonCppArray<VideoFileDetailsVideoStream > >(storage);
}

client::JsonCppArray<VideoFileDetailsVideoStream > VideoFileDetails::mutable_videoStreams() {
  Json::Value* storage = MutableStorage("videoStreams");
  return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<VideoFileDetailsVideoStream > >(storage);
}
}  // namespace google_youtube_api
