var annotated =
[
    [ "AbstractWebServer", "classgoogleapis_1_1client_1_1AbstractWebServer.html", "classgoogleapis_1_1client_1_1AbstractWebServer" ],
    [ "AuthorizationCredential", "classgoogleapis_1_1client_1_1AuthorizationCredential.html", "classgoogleapis_1_1client_1_1AuthorizationCredential" ],
    [ "Base64Codec", "classgoogleapis_1_1client_1_1Base64Codec.html", "classgoogleapis_1_1client_1_1Base64Codec" ],
    [ "Base64CodecFactory", "classgoogleapis_1_1client_1_1Base64CodecFactory.html", "classgoogleapis_1_1client_1_1Base64CodecFactory" ],
    [ "BaseServiceRequestPager", "classgoogleapis_1_1client_1_1BaseServiceRequestPager.html", "classgoogleapis_1_1client_1_1BaseServiceRequestPager" ],
    [ "ClientService", "classgoogleapis_1_1client_1_1ClientService.html", "classgoogleapis_1_1client_1_1ClientService" ],
    [ "ClientServiceRequest", "classgoogleapis_1_1client_1_1ClientServiceRequest.html", "classgoogleapis_1_1client_1_1ClientServiceRequest" ],
    [ "Codec", "classgoogleapis_1_1client_1_1Codec.html", "classgoogleapis_1_1client_1_1Codec" ],
    [ "CodecFactory", "classgoogleapis_1_1client_1_1CodecFactory.html", "classgoogleapis_1_1client_1_1CodecFactory" ],
    [ "CodecReader", "classgoogleapis_1_1client_1_1CodecReader.html", "classgoogleapis_1_1client_1_1CodecReader" ],
    [ "CredentialStore", "classgoogleapis_1_1client_1_1CredentialStore.html", "classgoogleapis_1_1client_1_1CredentialStore" ],
    [ "CredentialStoreFactory", "classgoogleapis_1_1client_1_1CredentialStoreFactory.html", "classgoogleapis_1_1client_1_1CredentialStoreFactory" ],
    [ "CurlHttpTransport", "classgoogleapis_1_1client_1_1CurlHttpTransport.html", "classgoogleapis_1_1client_1_1CurlHttpTransport" ],
    [ "CurlHttpTransportFactory", "classgoogleapis_1_1client_1_1CurlHttpTransportFactory.html", "classgoogleapis_1_1client_1_1CurlHttpTransportFactory" ],
    [ "DataReader", "classgoogleapis_1_1client_1_1DataReader.html", "classgoogleapis_1_1client_1_1DataReader" ],
    [ "DataWriter", "classgoogleapis_1_1client_1_1DataWriter.html", "classgoogleapis_1_1client_1_1DataWriter" ],
    [ "DateTime", "classgoogleapis_1_1client_1_1DateTime.html", "classgoogleapis_1_1client_1_1DateTime" ],
    [ "EncapsulatedServiceRequestPager< REQUEST, DATA >", "classgoogleapis_1_1client_1_1EncapsulatedServiceRequestPager.html", "classgoogleapis_1_1client_1_1EncapsulatedServiceRequestPager" ],
    [ "HttpEntryScribe::Entry", "classgoogleapis_1_1client_1_1HttpEntryScribe_1_1Entry.html", "classgoogleapis_1_1client_1_1HttpEntryScribe_1_1Entry" ],
    [ "Executor", "classgoogleapis_1_1thread_1_1Executor.html", "classgoogleapis_1_1thread_1_1Executor" ],
    [ "FileCredentialStoreFactory", "classgoogleapis_1_1client_1_1FileCredentialStoreFactory.html", "classgoogleapis_1_1client_1_1FileCredentialStoreFactory" ],
    [ "HtmlScribe", "classgoogleapis_1_1client_1_1HtmlScribe.html", "classgoogleapis_1_1client_1_1HtmlScribe" ],
    [ "HttpEntryScribe", "classgoogleapis_1_1client_1_1HttpEntryScribe.html", "classgoogleapis_1_1client_1_1HttpEntryScribe" ],
    [ "HttpRequest", "classgoogleapis_1_1client_1_1HttpRequest.html", "classgoogleapis_1_1client_1_1HttpRequest" ],
    [ "HttpRequestOptions", "classgoogleapis_1_1client_1_1HttpRequestOptions.html", "classgoogleapis_1_1client_1_1HttpRequestOptions" ],
    [ "HttpRequestState", "classgoogleapis_1_1client_1_1HttpRequestState.html", "classgoogleapis_1_1client_1_1HttpRequestState" ],
    [ "HttpResponse", "classgoogleapis_1_1client_1_1HttpResponse.html", "classgoogleapis_1_1client_1_1HttpResponse" ],
    [ "HttpScribe", "classgoogleapis_1_1client_1_1HttpScribe.html", "classgoogleapis_1_1client_1_1HttpScribe" ],
    [ "HttpScribeCensor", "classgoogleapis_1_1client_1_1HttpScribeCensor.html", "classgoogleapis_1_1client_1_1HttpScribeCensor" ],
    [ "HttpStatusCode", "classgoogleapis_1_1client_1_1HttpStatusCode.html", "classgoogleapis_1_1client_1_1HttpStatusCode" ],
    [ "HttpTransport", "classgoogleapis_1_1client_1_1HttpTransport.html", "classgoogleapis_1_1client_1_1HttpTransport" ],
    [ "HttpTransportErrorHandler", "classgoogleapis_1_1client_1_1HttpTransportErrorHandler.html", "classgoogleapis_1_1client_1_1HttpTransportErrorHandler" ],
    [ "HttpTransportFactory", "classgoogleapis_1_1client_1_1HttpTransportFactory.html", "classgoogleapis_1_1client_1_1HttpTransportFactory" ],
    [ "HttpTransportLayerConfig", "classgoogleapis_1_1client_1_1HttpTransportLayerConfig.html", "classgoogleapis_1_1client_1_1HttpTransportLayerConfig" ],
    [ "HttpTransportOptions", "classgoogleapis_1_1client_1_1HttpTransportOptions.html", "classgoogleapis_1_1client_1_1HttpTransportOptions" ],
    [ "HttpTransportTestFixture", "classgoogleapis_1_1HttpTransportTestFixture.html", "classgoogleapis_1_1HttpTransportTestFixture" ],
    [ "JsonCppAbstractIterator< DATA, ITERATOR >", "classgoogleapis_1_1client_1_1JsonCppAbstractIterator.html", "classgoogleapis_1_1client_1_1JsonCppAbstractIterator" ],
    [ "JsonCppArray< T >", "classgoogleapis_1_1client_1_1JsonCppArray.html", "classgoogleapis_1_1client_1_1JsonCppArray" ],
    [ "JsonCppAssociativeArray< T >", "classgoogleapis_1_1client_1_1JsonCppAssociativeArray.html", "classgoogleapis_1_1client_1_1JsonCppAssociativeArray" ],
    [ "JsonCppCapsule< BASE >", "classgoogleapis_1_1client_1_1JsonCppCapsule.html", "classgoogleapis_1_1client_1_1JsonCppCapsule" ],
    [ "JsonCppConstAssociativeIterator< T >", "classgoogleapis_1_1client_1_1JsonCppConstAssociativeIterator.html", "classgoogleapis_1_1client_1_1JsonCppConstAssociativeIterator" ],
    [ "JsonCppConstIndexIterator< T >", "classgoogleapis_1_1client_1_1JsonCppConstIndexIterator.html", "classgoogleapis_1_1client_1_1JsonCppConstIndexIterator" ],
    [ "JsonCppData", "classgoogleapis_1_1client_1_1JsonCppData.html", "classgoogleapis_1_1client_1_1JsonCppData" ],
    [ "JsonCppDictionary", "classgoogleapis_1_1client_1_1JsonCppDictionary.html", "classgoogleapis_1_1client_1_1JsonCppDictionary" ],
    [ "JsonPlaybackTransport", "classgoogleapis_1_1client_1_1JsonPlaybackTransport.html", "classgoogleapis_1_1client_1_1JsonPlaybackTransport" ],
    [ "JsonPlaybackTransportFactory", "classgoogleapis_1_1client_1_1JsonPlaybackTransportFactory.html", "classgoogleapis_1_1client_1_1JsonPlaybackTransportFactory" ],
    [ "JsonScribe", "classgoogleapis_1_1client_1_1JsonScribe.html", "classgoogleapis_1_1client_1_1JsonScribe" ],
    [ "MediaUploader", "classgoogleapis_1_1client_1_1MediaUploader.html", "classgoogleapis_1_1client_1_1MediaUploader" ],
    [ "MediaUploadSpec", "classgoogleapis_1_1client_1_1MediaUploadSpec.html", "classgoogleapis_1_1client_1_1MediaUploadSpec" ],
    [ "MockAuthorizationCredential", "classgoogleapis_1_1client_1_1MockAuthorizationCredential.html", "classgoogleapis_1_1client_1_1MockAuthorizationCredential" ],
    [ "MockHttpRequest", "classgoogleapis_1_1client_1_1MockHttpRequest.html", "classgoogleapis_1_1client_1_1MockHttpRequest" ],
    [ "MockHttpTransport", "classgoogleapis_1_1client_1_1MockHttpTransport.html", "classgoogleapis_1_1client_1_1MockHttpTransport" ],
    [ "MockHttpTransportErrorHandler", "classgoogleapis_1_1client_1_1MockHttpTransportErrorHandler.html", "classgoogleapis_1_1client_1_1MockHttpTransportErrorHandler" ],
    [ "MockHttpTransportFactory", "classgoogleapis_1_1client_1_1MockHttpTransportFactory.html", "classgoogleapis_1_1client_1_1MockHttpTransportFactory" ],
    [ "MongooseWebServer", "classgoogleapis_1_1client_1_1MongooseWebServer.html", "classgoogleapis_1_1client_1_1MongooseWebServer" ],
    [ "OAuth2AuthorizationFlow", "classgoogleapis_1_1client_1_1OAuth2AuthorizationFlow.html", "classgoogleapis_1_1client_1_1OAuth2AuthorizationFlow" ],
    [ "OAuth2ClientSpec", "classgoogleapis_1_1client_1_1OAuth2ClientSpec.html", "classgoogleapis_1_1client_1_1OAuth2ClientSpec" ],
    [ "OAuth2Credential", "classgoogleapis_1_1client_1_1OAuth2Credential.html", "classgoogleapis_1_1client_1_1OAuth2Credential" ],
    [ "OAuth2ExchangeAuthorizationCodeRequest", "classgoogleapis_1_1client_1_1OAuth2ExchangeAuthorizationCodeRequest.html", "classgoogleapis_1_1client_1_1OAuth2ExchangeAuthorizationCodeRequest" ],
    [ "OAuth2InstalledApplicationFlow", "classgoogleapis_1_1client_1_1OAuth2InstalledApplicationFlow.html", "classgoogleapis_1_1client_1_1OAuth2InstalledApplicationFlow" ],
    [ "OAuth2PendingAuthorizations< CALLBACK >", "classgoogleapis_1_1client_1_1OAuth2PendingAuthorizations.html", "classgoogleapis_1_1client_1_1OAuth2PendingAuthorizations" ],
    [ "OAuth2RefreshTokenRequest", "classgoogleapis_1_1client_1_1OAuth2RefreshTokenRequest.html", "classgoogleapis_1_1client_1_1OAuth2RefreshTokenRequest" ],
    [ "OAuth2RequestOptions", "structgoogleapis_1_1client_1_1OAuth2RequestOptions.html", "structgoogleapis_1_1client_1_1OAuth2RequestOptions" ],
    [ "OAuth2RevokeTokenRequest", "classgoogleapis_1_1client_1_1OAuth2RevokeTokenRequest.html", "classgoogleapis_1_1client_1_1OAuth2RevokeTokenRequest" ],
    [ "OAuth2TokenRequest", "classgoogleapis_1_1client_1_1OAuth2TokenRequest.html", "classgoogleapis_1_1client_1_1OAuth2TokenRequest" ],
    [ "OAuth2WebApplicationFlow", "classgoogleapis_1_1client_1_1OAuth2WebApplicationFlow.html", "classgoogleapis_1_1client_1_1OAuth2WebApplicationFlow" ],
    [ "OpenSslCodec", "classgoogleapis_1_1client_1_1OpenSslCodec.html", "classgoogleapis_1_1client_1_1OpenSslCodec" ],
    [ "OpenSslCodecFactory", "classgoogleapis_1_1client_1_1OpenSslCodecFactory.html", "classgoogleapis_1_1client_1_1OpenSslCodecFactory" ],
    [ "ParsedUrl", "classgoogleapis_1_1client_1_1ParsedUrl.html", "classgoogleapis_1_1client_1_1ParsedUrl" ],
    [ "RequestHeaderLess", "structgoogleapis_1_1client_1_1RequestHeaderLess.html", "structgoogleapis_1_1client_1_1RequestHeaderLess" ],
    [ "SensitiveFileUtils", "classgoogleapis_1_1client_1_1SensitiveFileUtils.html", "classgoogleapis_1_1client_1_1SensitiveFileUtils" ],
    [ "SerializableJson", "classgoogleapis_1_1client_1_1SerializableJson.html", "classgoogleapis_1_1client_1_1SerializableJson" ],
    [ "ServiceRequestPager< REQUEST, DATA >", "classgoogleapis_1_1client_1_1ServiceRequestPager.html", "classgoogleapis_1_1client_1_1ServiceRequestPager" ],
    [ "Status", "classgoogleapis_1_1util_1_1Status.html", "classgoogleapis_1_1util_1_1Status" ],
    [ "ThreadsafePrimitive< T >", "classgoogleapis_1_1client_1_1ThreadsafePrimitive.html", "classgoogleapis_1_1client_1_1ThreadsafePrimitive" ],
    [ "ThreadsafeString", "classgoogleapis_1_1client_1_1ThreadsafeString.html", "classgoogleapis_1_1client_1_1ThreadsafeString" ],
    [ "UriTemplate", "classgoogleapis_1_1client_1_1UriTemplate.html", "classgoogleapis_1_1client_1_1UriTemplate" ],
    [ "VersionInfo", "classgoogleapis_1_1client_1_1VersionInfo.html", "classgoogleapis_1_1client_1_1VersionInfo" ],
    [ "WebServerAuthorizationCodeGetter", "classgoogleapis_1_1client_1_1WebServerAuthorizationCodeGetter.html", "classgoogleapis_1_1client_1_1WebServerAuthorizationCodeGetter" ],
    [ "WebServerRequest", "classgoogleapis_1_1client_1_1WebServerRequest.html", "classgoogleapis_1_1client_1_1WebServerRequest" ],
    [ "WebServerResponse", "classgoogleapis_1_1client_1_1WebServerResponse.html", "classgoogleapis_1_1client_1_1WebServerResponse" ]
];