// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Wax API (wax/v1)
// Generated from:
//   Version: v1
//   Revision: 20130321
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.3
#ifndef  GOOGLE_WAX_API_WAX_REMOVE_SESSION_RESPONSE_H_
#define  GOOGLE_WAX_API_WAX_REMOVE_SESSION_RESPONSE_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_wax_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class WaxRemoveSessionResponse : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static WaxRemoveSessionResponse* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit WaxRemoveSessionResponse(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit WaxRemoveSessionResponse(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~WaxRemoveSessionResponse();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_wax_api::WaxRemoveSessionResponse</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_wax_api::WaxRemoveSessionResponse");
  }

  /**
   * Determine if the '<code>kind</code>' attribute was set.
   *
   * @return true if the '<code>kind</code>' attribute was set.
   */
  bool has_kind() const {
    return Storage().isMember("kind");
  }

  /**
   * Clears the '<code>kind</code>' attribute.
   */
  void clear_kind() {
    MutableStorage()->removeMember("kind");
  }


  /**
   * Get the value of the '<code>kind</code>' attribute.
   */
  const StringPiece get_kind() const {
    const Json::Value& v = Storage("kind");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>kind</code>' attribute.
   *
   * The kind of object this is.
   *
   * @param[in] value The new value.
   */
  void set_kind(const StringPiece& value) {
    *MutableStorage("kind") = value.data();
  }

  /**
   * Determine if the '<code>removedSessionId</code>' attribute was set.
   *
   * @return true if the '<code>removedSessionId</code>' attribute was set.
   */
  bool has_removed_session_id() const {
    return Storage().isMember("removedSessionId");
  }

  /**
   * Clears the '<code>removedSessionId</code>' attribute.
   */
  void clear_removed_session_id() {
    MutableStorage()->removeMember("removedSessionId");
  }


  /**
   * Get the value of the '<code>removedSessionId</code>' attribute.
   */
  const StringPiece get_removed_session_id() const {
    const Json::Value& v = Storage("removedSessionId");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>removedSessionId</code>' attribute.
   *
   * The ID corresponding to the session that was removed.
   *
   * @param[in] value The new value.
   */
  void set_removed_session_id(const StringPiece& value) {
    *MutableStorage("removedSessionId") = value.data();
  }

 private:
  void operator=(const WaxRemoveSessionResponse&);
};  // WaxRemoveSessionResponse
}  // namespace google_wax_api
#endif  // GOOGLE_WAX_API_WAX_REMOVE_SESSION_RESPONSE_H_
