// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Calendar API (calendar/v3)
// Description:
//   Manipulates events and other calendar data.
// Classes:
//   CalendarList
// Documentation:
//   https://developers.google.com/google-apps/calendar/firstapp

#include "google/calendar_api/calendar_list.h"
#include <string>
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/calendar_api/calendar_list_entry.h"


#include <string>
#include "googleapis/strings/strcat.h"

namespace google_calendar_api {
using namespace googleapis;


// Object factory method (static).
CalendarList* CalendarList::New() {
  return new client::JsonCppCapsule<CalendarList>;
}

// Standard immutable constructor.
CalendarList::CalendarList(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
CalendarList::CalendarList(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
CalendarList::~CalendarList() {
}

// Properties.

const client::JsonCppArray<CalendarListEntry > CalendarList::get_items() const {
   const Json::Value& storage = Storage("items");
   return client::JsonValueToCppValueHelper<client::JsonCppArray<CalendarListEntry > >(storage);
}

client::JsonCppArray<CalendarListEntry > CalendarList::mutable_items() {
  Json::Value* storage = MutableStorage("items");
  return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<CalendarListEntry > >(storage);
}
}  // namespace google_calendar_api
