// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.0
//   Build date: 2014-11-17 18:43:33 UTC
//   on: 2014-12-19, 09:55:43 UTC
//   C++ generator version:

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Calendar API (calendar/v3)
// Description:
//   Lets you manipulate events and other calendar data.
// Classes:
//   CalendarListEntry
// Documentation:
//   https://developers.google.com/google-apps/calendar/firstapp

#include "google/calendar_api/calendar_list_entry.h"
#include <string>
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/calendar_api/calendar_notification.h"
#include "google/calendar_api/event_reminder.h"


#include <string>
#include "googleapis/strings/strcat.h"

namespace google_calendar_api {
using namespace googleapis;



// Object factory method (static).
CalendarListEntry::CalendarListEntryNotificationSettings* CalendarListEntry::CalendarListEntryNotificationSettings::New() {
  return new client::JsonCppCapsule<CalendarListEntryNotificationSettings>;
}

// Standard immutable constructor.
CalendarListEntry::CalendarListEntryNotificationSettings::CalendarListEntryNotificationSettings(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
CalendarListEntry::CalendarListEntryNotificationSettings::CalendarListEntryNotificationSettings(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
CalendarListEntry::CalendarListEntryNotificationSettings::~CalendarListEntryNotificationSettings() {
}
// Object factory method (static).
CalendarListEntry* CalendarListEntry::New() {
  return new client::JsonCppCapsule<CalendarListEntry>;
}

// Standard immutable constructor.
CalendarListEntry::CalendarListEntry(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
CalendarListEntry::CalendarListEntry(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
CalendarListEntry::~CalendarListEntry() {
}
}  // namespace google_calendar_api
